### ISSUE TITLE
how  can i get your paper, I searched in google scholar, but there is no relative paper, would you mind give a link?

### ISSUE THREAD

**Issue by Asherchi** [GuiyuZhao/VRHCF#1]

**Comment by GuiyuZhao** [comment]
Thank you for your attention. My paper is under review and the result will be available in March. Whether accepted or rejected, I'll post it on arxiv.

**Comment by Asherchi** [comment]
I sincerely hope your paper will be accepted and look forward to it!

**Comment by GuiyuZhao** [comment]
Our paper in arXiv version is now available.
